### ISSUE TITLE
コメントをするとエラーがでます。

### ISSUE THREAD

**Issue by mikik0** [mikik0/Uturn#2]
# エラー内容
- ActiveRecord::RecordNotFound at /prefectiures/:id/contributions/:c_id/comments
Couldn’t find Contribution with ‘id’=:c_id
- 投稿内容にコメントをつけて送信をするとエラーが出ます。

# 概要
- コメント投稿後、コメント一覧に新しいコメントが追加されている状態のページに行けるようにしたい。
- エラーが出ていても、コメントは投稿することができる。

# 自分の考え
- @contribution = Contribution.find(params[:c_id])を@contribution = Contribution.find(2)とかにするとエラーが消えたので、params[:c_id]がうまく行っていない？
p params[:c_id]はちゃんと動作するのですが、原因がよくわからないです。

# 調べた記事とか、実装の参考にした記事
https://ja.stackoverflow.com/questions/59906/couldnt-find-with-id%E3%81%AE%E8%A7%A3%E6%B1%BA%E6%96%B9%E6%B3%95-%E3%82%B7%E3%83%A7%E3%83%83%E3%83%94%E3%83%B3%E3%82%B0%E3%82%AB%E3%83%BC%E3%83%88%E6%A9%9F%E8%83%BD%E3%81%AE%E5%AE%9F%E8%A3%85

https://programming-beginner-zeroichi.jp/articles/45

**Comment by kohey** [comment]
原因としては、コメントを投稿したときの `redirect` 先で画像の通り、`params` に入ってきてるデータが数字になっていないからです。

これは`redirect "/prefectiures/:id/contributions/:c_id/comments"` の id 部分が文字列になっていることが原因なので、ここを修正すればいけるかと！

修正方法についてはちょっと考えてもらえれば！
<img width="790" alt="スクリーンショット 2020-06-17 13 04 09" src="https://user-images.githubusercontent.com/36844012/84853996-71917900-b09b-11ea-92d4-589eb1d8bcca.png">

**Comment by mikik0** [comment]
ありがとうございます！
なおりました。
